version: '3'
services:
  service:
    build: ./server
    ports:
     - "5000:5555"
    depends_on:
     - mongo
    environment:
     - SmtpOptions__FromAddress=${SmtpOptions__FromAddress}
     - SmtpOptions__FromAddressTitle=${SmtpOptions__FromAddressTitle}
     - SmtpOptions__Password=${SmtpOptions__Password}
  mongo:
    image: "mongo:3.4"
  proxy:
    build: ./client
    ports: 
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - service
