version: '3.2'
services:
  service:
    build: ./server
    ports:
     - "5000:5555"
    depends_on:
     - mongo
    environment:
     - SmtpOptions__FromAddress=${SmtpOptions__FromAddress}
     - SmtpOptions__FromAddressTitle=${SmtpOptions__FromAddressTitle}
     - SmtpOptions__Password=${SmtpOptions__Password}
    volumes:
      - type: bind
        source: ${content_folder}
        target: /content
  mongo:
    image: "mongo:3.4"
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
  proxy:
    build: ./client
    ports: 
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - service
    volumes:
      - type: bind
        source: ${content_folder}
        target: /data/content

volumes:
  mongo_data: