version: '3'
services:
  service:
    build: ./server
    ports:
     - "5000:5555"
    depends_on:
     - mongo
  mongo:
    image: "mongo:3.4"
  proxy:
    build: ./nginx
    ports: 
      - "80:80"
    depends_on:
      - service
